### ISSUE TITLE
So..  how do i do this?

### ISSUE THREAD

**Issue by xicst1** [SuchACharles/lightning#1]
My man, in all honesty, how am i supposed to run this software? i watched the youtube tutorial but from since the page seems to have changed and there is no .exe and only code which i don't know how to make work. Maybe im missing something?

**Comment by SuchACharles** [comment]
This repo is for the new version I am currently building on a new framework, to find the original versions of Lightning please go here: https://github.com/SuchACharles/Lightning-Original/releases

**Comment by xicst1** [comment]
Thanks bro!
